name: Event Demo 1
on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main
      - dev*
      - featire/**
  workflow_dispatch:
  push:
    branches:
      - main
      - dev*
      - feature/**
    # paths-ignore:
    #   - '.github/workflows/*'
    # paths:
    #   - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install depedncies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "deploying..."
